# We run this workflow on the base ocp-ci-analysis container image which contains dependencies neccesary to run these notebooks 
name: Optimal Stopping Point 

# Controls when the workflow will run
on:

  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

  jobs:
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: quay.io/aicoe/ocp-ci-analysis
    if: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }} == true
       
    env:
      GITHUB_REPO: ${{ github.event.client_payload.REPO || secrets.REPO }}
      GITHUB_ORG: ${{ github.event.client_payload.ORG || secrets.ORG }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}


      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Setup Python environment
          uses: actions/setup-python@v2
          with:
           python-version: '3.8'
        - name: Install dependencies
          run: | 
            python -m pip install --upgrade pip 
            pip install -r requirements.txt

        - name: Run Jupyter Notebook
          uses: actions/starter-workflows/jupyter-notebook-action@main
          with:
            path: notebooks/access_github_ci_data.ipynb